spring:
  datasource:
      druid:
        url: jdbc:mysql://localhost:3306/fmmall2?characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 875803136
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher


mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qfedu.fmmal.entity
  
server:
  port: 8080

